# Numpy - DS

In [5]:
import numpy as np
np.random.seed(42)

In [3]:
x = (2.0, 4, '6.0', 3, 4.2)
y = np.array(tuple(x))

In [4]:
y

array(['2.0', '4', '6.0', '3', '4.2'], dtype='<U32')

### Multi-dimensional arrays


In [23]:
y = np.random.randint(0,20, (4,3,3,2))
y

array([[[[ 6, 19],
         [14, 10],
         [ 7,  6]],

        [[18, 10],
         [10,  3],
         [ 7,  2]],

        [[ 1, 11],
         [ 5,  1],
         [ 0, 11]]],


       [[[11, 16],
         [ 9, 15],
         [14, 14]],

        [[18, 11],
         [19,  2],
         [ 4, 18]],

        [[ 6,  8],
         [ 6, 17],
         [ 3, 13]]],


       [[[17,  8],
         [ 1, 19],
         [14,  6]],

        [[11,  7],
         [14,  2],
         [13, 16]],

        [[ 3, 17],
         [ 7,  3],
         [ 1,  5]]],


       [[[ 9,  3],
         [17, 11],
         [ 1,  9]],

        [[ 3, 13],
         [15, 14],
         [ 7, 13]],

        [[ 7, 15],
         [12, 17],
         [14, 12]]]])

In [27]:
m = np.random.randint(1,10,(3,3,2))
m

array([[[3, 1],
        [8, 3],
        [3, 1]],

       [[5, 7],
        [9, 7],
        [9, 8]],

       [[2, 1],
        [7, 7],
        [8, 5]]])

In [28]:
m.ravel()

array([3, 1, 8, 3, 3, 1, 5, 7, 9, 7, 9, 8, 2, 1, 7, 7, 8, 5])

In [29]:
m.reshape(2,9)

array([[3, 1, 8, 3, 3, 1, 5, 7, 9],
       [7, 9, 8, 2, 1, 7, 7, 8, 5]])

In [30]:
x = (2.0, 4, 6.0, 3, 4.2)
y = np.array(x,dtype=int)

In [31]:
y

array([2, 4, 6, 3, 4])

In [33]:
np.random.rand(3,3)

array([[0.4937956 , 0.52273283, 0.42754102],
       [0.02541913, 0.10789143, 0.03142919],
       [0.63641041, 0.31435598, 0.50857069]])

### Slicing

In [36]:
x = np.random.randn(3,3)

In [39]:
x[1:,1:]

array([[-0.32766215, -0.39210815],
       [ 0.29612028,  0.26105527]])

In [40]:
x[::2,::2]

array([[ 0.51326743,  0.96864499],
       [-1.46351495,  0.26105527]])

In [41]:
x[::-1,::-1]

array([[ 0.26105527,  0.29612028, -1.46351495],
       [-0.39210815, -0.32766215, -0.70205309],
       [ 0.96864499,  0.09707755,  0.51326743]])

In [43]:
x.T

array([[ 0.51326743, -0.70205309, -1.46351495],
       [ 0.09707755, -0.32766215,  0.29612028],
       [ 0.96864499, -0.39210815,  0.26105527]])

### Splitting of arrays

In [13]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 4])
print(x1, x2, x3)

[1 2 3] [99] [99  3  2  1]


In [14]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [16]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
