In [134]:
import numpy as np
import pandas as pd

In [135]:
df = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')

In [136]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [137]:
data = pd.Series([0.25,0.5,0.75,1.0])

In [138]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [139]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [140]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [141]:
data.shape

(4,)

In [142]:
data[[0,1,3]]

0    0.25
1    0.50
3    1.00
dtype: float64

In [143]:
data[:2]

0    0.25
1    0.50
dtype: float64

In [144]:
data = pd.Series([0.25,0.5,0.75,1.0], index = ['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [145]:
data['c']

0.75

In [146]:
data = pd.Series([0.25,0.5,0.75,1.0], index = list(range(0,7,2)))
data

0    0.25
2    0.50
4    0.75
6    1.00
dtype: float64

In [147]:
# series using dist

In [148]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [149]:
population['Florida']

19552860

In [150]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [151]:
k = pd.Series({2:'a', 1:'b', 3:'c'}, index = [3,5])
k

3      c
5    NaN
dtype: object

In [152]:
area_dict = {'Florida': 423967, 'Texas': 695662, 'New York': 141297,
             'California': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

Florida       423967
Texas         695662
New York      141297
California    170312
Illinois      149995
dtype: int64

In [153]:
states  = pd.DataFrame({'pop': population,
                       'ara': area})
states

pop     ara
California  38332521  170312
Florida     19552860  423967
Illinois    12882135  149995
New York    19651127  141297
Texas       26448193  695662

In [154]:
states.columns

Index(['pop', 'ara'], dtype='object')

In [155]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [156]:
states.values

array([[38332521,   170312],
       [19552860,   423967],
       [12882135,   149995],
       [19651127,   141297],
       [26448193,   695662]], dtype=int64)

In [157]:
states['pop']

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
Name: pop, dtype: int64

In [158]:
df.describe(include = 'all')

sepal.length  sepal.width  petal.length  petal.width    variety
count     150.000000   150.000000    150.000000   150.000000        150
unique           NaN          NaN           NaN          NaN          3
top              NaN          NaN           NaN          NaN  Virginica
freq             NaN          NaN           NaN          NaN         50
mean        5.843333     3.057333      3.758000     1.199333        NaN
std         0.828066     0.435866      1.765298     0.762238        NaN
min         4.300000     2.000000      1.000000     0.100000        NaN
25%         5.100000     2.800000      1.600000     0.300000        NaN
50%         5.800000     3.000000      4.350000     1.300000        NaN
75%         6.400000     3.300000      5.100000     1.800000        NaN
max         7.900000     4.400000      6.900000     2.500000        NaN

In [159]:
df.tail()

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [160]:
df.variety.value_counts()

Virginica     50
Setosa        50
Versicolor    50
Name: variety, dtype: int64

In [161]:
df.variety.unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [162]:
df['sepal.length'] [df['sepal.length'] > 4.5]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 145, dtype: float64

In [163]:
df1 = df.iloc[:,:]

In [164]:
df1.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [165]:
df2 = df1[df1['sepal.length'] > 2.5]

In [166]:
df2['sepal.length'].value_counts()

5.0    10
6.3     9
5.1     9
6.7     8
5.7     8
5.5     7
5.8     7
6.4     7
6.0     6
4.9     6
6.1     6
5.4     6
5.6     6
6.5     5
4.8     5
7.7     4
6.9     4
5.2     4
6.2     4
4.6     4
7.2     3
6.8     3
4.4     3
5.9     3
6.6     2
4.7     2
7.6     1
7.4     1
4.3     1
7.9     1
7.3     1
7.0     1
4.5     1
5.3     1
7.1     1
Name: sepal.length, dtype: int64

In [167]:
df2 = df1[(df1['sepal.length'] > 2.5) & (df1['sepal.width']>3)]['petal.width']

In [168]:
df2

0      0.2
2      0.2
3      0.2
4      0.2
5      0.4
      ... 
140    2.4
141    2.3
143    2.3
144    2.5
148    2.3
Name: petal.width, Length: 67, dtype: float64

In [169]:
df2 = df1.loc[(df1['sepal.length'] > 2.5) & (df1['sepal.width']>3),'petal.width']

In [170]:
df2.value_counts()

0.2    25
0.4     7
2.3     5
0.3     5
1.8     3
0.1     3
2.5     3
1.5     3
1.4     2
2.1     2
2.4     2
1.6     2
2.0     2
2.2     1
0.6     1
0.5     1
Name: petal.width, dtype: int64

In [171]:
np.nan +2

nan

In [172]:
df2.values

array([0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.1, 0.2, 0.2, 0.2, 0.4, 0.4,
       0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2,
       0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2, 0.3, 0.2, 0.6, 0.4, 0.2,
       0.2, 0.2, 0.2, 1.4, 1.5, 1.5, 1.6, 1.4, 1.8, 1.6, 1.5, 2.5, 2.5,
       2. , 2.3, 2.2, 2.3, 2.1, 1.8, 2. , 2.4, 1.8, 2.1, 2.4, 2.3, 2.3,
       2.5, 2.3])

In [173]:
def sum(a,b):
    return a + b
x = sum(3,5)
x

8

In [174]:
# numpy slicing use .values[]

In [175]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [176]:
df.iloc[:,:]

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [177]:
df5 = df.sample(50)

In [178]:
df6 = df5.head(10)

In [179]:
df5.loc[df5.variety == 'Versicolor',:].iloc[:10,:]

sepal.length  sepal.width  petal.length  petal.width     variety
58           6.6          2.9           4.6          1.3  Versicolor
57           4.9          2.4           3.3          1.0  Versicolor
83           6.0          2.7           5.1          1.6  Versicolor
97           6.2          2.9           4.3          1.3  Versicolor
95           5.7          3.0           4.2          1.2  Versicolor
75           6.6          3.0           4.4          1.4  Versicolor
72           6.3          2.5           4.9          1.5  Versicolor
85           6.0          3.4           4.5          1.6  Versicolor
92           5.8          2.6           4.0          1.2  Versicolor
79           5.7          2.6           3.5          1.0  Versicolor

In [180]:
import seaborn as sns
df = sns.load_dataset('tips')

In [181]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [182]:
df.loc[(df.sex == 'Male') & (df.smoker == 'No')].mean()

total_bill    19.791237
tip            3.113402
size           2.711340
dtype: float64

In [183]:
tips = df.groupby(['sex']).mean()['tip']

In [184]:
df = df.groupby(['sex','smoker']).max()['tip']
df

sex     smoker
Male    Yes       10.0
        No         9.0
Female  Yes        6.5
        No         5.2
Name: tip, dtype: float64

In [185]:
df[:,'No']

sex
Male      9.0
Female    5.2
Name: tip, dtype: float64

In [186]:
df.groupby(['sex','smoker']).max()

sex     smoker
Male    Yes       10.0
        No         9.0
Female  Yes        6.5
        No         5.2
Name: tip, dtype: float64

In [187]:
df

sex     smoker
Male    Yes       10.0
        No         9.0
Female  Yes        6.5
        No         5.2
Name: tip, dtype: float64

In [188]:
df.xs('No', level ='smoker')

sex
Male      9.0
Female    5.2
Name: tip, dtype: float64